server:
  port: 8080

spring:
  application:
    name: interview-simulator

  datasource:
    url: jdbc:mysql://192.168.81.100:3306/ai_interview
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.81.100
      port: 6379
      database: 0
      password: 888888
      ttl: 3600

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.interview: debug
